export const products = [
  {
    id: "fraud-detection",
    slug: "fraud-detection",
    tagline: "DETECT FRAUD IN REAL-TIME",
    name: "Fraud Detection",
    shortDescription: "AI-powered transaction monitoring and behavioral analysis to prevent financial fraud before it happens.",
    description: "Our advanced Fraud Detection AI leverages machine learning and behavioral analytics to identify suspicious patterns in real-time. By analyzing transaction data, user behavior, and contextual signals, we help financial institutions and enterprises prevent fraud before it impacts their bottom line.",
    iconName: "Shield" as const,
    color: "#fcd34d",
    gradient: "from-yellow-400 to-amber-500",
    hasVideo: true,
    videoSrc: "/video/Yellowsense-fraud-detection-animation.mp4",
    features: [
      "Real-time transaction monitoring",
      "Behavioral pattern analysis",
      "Machine learning risk scoring",
      "Automated alert generation",
      "Integration with existing systems",
      "Customizable fraud rules engine",
    ],
    benefits: [
      { title: "99.9% Accuracy", description: "Industry-leading fraud detection accuracy" },
      { title: "< 100ms Response", description: "Real-time detection with minimal latency" },
      { title: "50% Cost Reduction", description: "Reduce fraud investigation costs" },
    ],
  },
  {
    id: "fault-detection",
    slug: "fault-detection",
    tagline: "PREDICT FAILURES BEFORE THEY OCCUR",
    name: "Industrial Fault Detection",
    shortDescription: "Advanced sensing solutions for real-time fault detection and predictive maintenance in industrial systems.",
    description: "Our Industrial Fault Detection system uses IoT sensors and AI algorithms to monitor equipment health in real-time. By predicting failures before they occur, we help manufacturers reduce downtime, extend equipment life, and optimize maintenance schedules.",
    iconName: "Cpu" as const,
    color: "#fbbf24",
    gradient: "from-amber-400 to-orange-500",
    hasVideo: true,
    videoSrc: "/video/sensor-final-1764092032100.mp4",
    features: [
      "IoT sensor integration",
      "Predictive maintenance algorithms",
      "Equipment health monitoring",
      "Anomaly detection",
      "Maintenance scheduling optimization",
      "Historical data analysis",
    ],
    benefits: [
      { title: "40% Less Downtime", description: "Predict and prevent equipment failures" },
      { title: "30% Cost Savings", description: "Optimize maintenance operations" },
      { title: "2x Equipment Life", description: "Extend asset lifespan with proactive care" },
    ],
  },
  {
    id: "clean-rooms",
    slug: "clean-rooms",
    tagline: "SECURE DATA ENVIRONMENTS",
    name: "Confidential Clean Rooms",
    shortDescription: "Secure, compliant data environments for sensitive data processing with advanced privacy controls.",
    description: "Our Confidential Clean Rooms provide isolated, secure environments for processing sensitive data. With advanced encryption, access controls, and compliance features, organizations can collaborate on data while maintaining privacy and regulatory compliance.",
    iconName: "Database" as const,
    color: "#fcd34d",
    gradient: "from-yellow-400 to-lime-500",
    hasVideo: false,
    features: [
      "End-to-end encryption",
      "Granular access controls",
      "Audit trail logging",
      "Compliance certifications",
      "Secure data sharing",
      "Privacy-preserving analytics",
    ],
    benefits: [
      { title: "100% Compliant", description: "Meet GDPR, HIPAA, and SOC2 requirements" },
      { title: "Zero Trust", description: "No data exposure during processing" },
      { title: "Secure Collaboration", description: "Share insights without sharing data" },
    ],
  },
  {
    id: "analytics",
    slug: "analytics",
    tagline: "UNCOVER HIDDEN INSIGHTS",
    name: "Data Analytics",
    shortDescription: "Big data fusion and analytics platform for comprehensive threat intelligence and business insights.",
    description: "Our Data Analytics platform transforms raw data into actionable insights. By fusing multiple data sources and applying advanced analytics, we help organizations uncover patterns, identify opportunities, and make data-driven decisions with confidence.",
    iconName: "LineChart" as const,
    color: "#fde047",
    gradient: "from-yellow-300 to-amber-400",
    hasVideo: false,
    features: [
      "Multi-source data fusion",
      "Real-time dashboards",
      "Predictive analytics",
      "Custom report generation",
      "API integrations",
      "Machine learning models",
    ],
    benefits: [
      { title: "360° View", description: "Unified view across all data sources" },
      { title: "Faster Decisions", description: "Real-time insights for quick action" },
      { title: "Predictive Power", description: "Anticipate trends before they happen" },
    ],
  },
  {
    id: "cybersecurity",
    slug: "cybersecurity",
    tagline: "PROTECT YOUR DIGITAL ASSETS",
    name: "Cybersecurity",
    shortDescription: "Proactive threat detection and security audits to safeguard your critical infrastructure.",
    description: "Our Cybersecurity solutions provide comprehensive protection against digital threats. From vulnerability assessments to continuous monitoring, we help organizations identify and mitigate risks before they become breaches.",
    iconName: "Lock" as const,
    color: "#fbbf24",
    gradient: "from-amber-400 to-red-500",
    hasVideo: false,
    features: [
      "Vulnerability assessment",
      "Penetration testing",
      "24/7 threat monitoring",
      "Incident response",
      "Security awareness training",
      "Compliance auditing",
    ],
    benefits: [
      { title: "24/7 Protection", description: "Round-the-clock security monitoring" },
      { title: "Proactive Defense", description: "Stop threats before they strike" },
      { title: "Risk Mitigation", description: "Identify and fix vulnerabilities" },
    ],
  },
  {
    id: "nanny-verification",
    slug: "nanny-verification",
    tagline: "TRUST & SAFETY FOR FAMILIES",
    name: "Nanny Verification",
    shortDescription: "Comprehensive background verification and monitoring for domestic help and childcare providers.",
    description: "Our Nanny Verification service provides peace of mind for families. Through rigorous background checks, identity verification, and continuous monitoring, we help families ensure the safety and trustworthiness of their domestic help and childcare providers.",
    iconName: "Users" as const,
    color: "#f472b6",
    gradient: "from-pink-400 to-rose-500",
    hasVideo: false,
    features: [
      "Identity verification",
      "Criminal background checks",
      "Employment history verification",
      "Reference checks",
      "Continuous monitoring",
      "Digital trust scores",
    ],
    benefits: [
      { title: "Peace of Mind", description: "Know who you're welcoming into your home" },
      { title: "Verified Trust", description: "Comprehensive background screening" },
      { title: "Ongoing Safety", description: "Continuous monitoring for changes" },
    ],
  },
]

export type Product = typeof products[number]
export type IconName = Product["iconName"]

export function getProductBySlug(slug: string): Product | undefined {
  return products.find((p) => p.slug === slug)
}
