export const products = [
  {
    id: "fraud-detection",
    slug: "fraud-detection",
    tagline: "DETECT FRAUD IN REAL-TIME",
    name: "Fraud Detection",
    shortDescription: "AI-powered transaction monitoring and behavioral analysis to prevent financial fraud before it happens.",
    description: "Our advanced Fraud Detection AI leverages machine learning and behavioral analytics to identify suspicious patterns in real-time. By analyzing transaction data, user behavior, and contextual signals, we help financial institutions and enterprises prevent fraud before it impacts their bottom line.",
    iconName: "Shield" as const,
    color: "#eab308", // Yellow-500
    gradient: "from-yellow-500 to-amber-600",
    hasVideo: true,
    videoSrc: "/video/Yellowsense-fraud-detection-animation.mp4",
    features: [
      "Real-time transaction monitoring",
      "Behavioral pattern analysis",
      "Machine learning risk scoring",
      "Automated alert generation",
      "Integration with existing systems",
      "Customizable fraud rules engine",
    ],
    benefits: [
      { title: "99.9% Accuracy", description: "Industry-leading fraud detection accuracy" },
      { title: "< 100ms Response", description: "Real-time detection with minimal latency" },
      { title: "50% Cost Reduction", description: "Reduce fraud investigation costs" },
    ],
  },
  {
    id: "fault-detection",
    slug: "fault-detection",
    tagline: "PREDICT FAILURES BEFORE THEY OCCUR",
    name: "Industrial Fault Detection",
    shortDescription: "Advanced sensing solutions for real-time fault detection and predictive maintenance in industrial systems.",
    description: "Our Industrial Fault Detection system uses IoT sensors and AI algorithms to monitor equipment health in real-time. By predicting failures before they occur, we help manufacturers reduce downtime, extend equipment life, and optimize maintenance schedules.",
    iconName: "Cpu" as const,
    color: "#f97316", // Orange-500
    gradient: "from-orange-500 to-red-600",
    hasVideo: true,
    videoSrc: "/video/sensor-final-1764092032100.mp4",
    features: [
      "IoT sensor integration",
      "Predictive maintenance algorithms",
      "Equipment health monitoring",
      "Anomaly detection",
      "Maintenance scheduling optimization",
      "Historical data analysis",
    ],
    benefits: [
      { title: "40% Less Downtime", description: "Predict and prevent equipment failures" },
      { title: "30% Cost Savings", description: "Optimize maintenance operations" },
      { title: "2x Equipment Life", description: "Extend asset lifespan with proactive care" },
    ],
  },
  {
    id: "clean-rooms",
    slug: "clean-rooms",
    tagline: "SECURE DATA ENVIRONMENTS",
    name: "Confidential Clean Rooms",
    shortDescription: "Secure, compliant data environments for sensitive data processing with advanced privacy controls.",
    description: "Our Confidential Clean Rooms provide isolated, secure environments for processing sensitive data. With advanced encryption, access controls, and compliance features, organizations can collaborate on data while maintaining privacy and regulatory compliance.",
    iconName: "Database" as const,
    color: "#10b981", // Emerald-500
    gradient: "from-emerald-500 to-teal-600",
    hasVideo: true,
    videoSrc: "/video/YellowSense-jkcement-full-demo.mp4",
    features: [
      "End-to-end encryption",
      "Granular access controls",
      "Audit trail logging",
      "Compliance certifications",
      "Secure data sharing",
      "Privacy-preserving analytics",
    ],
    benefits: [
      { title: "100% Compliant", description: "Meet GDPR, HIPAA, and SOC2 requirements" },
      { title: "Zero Trust", description: "No data exposure during processing" },
      { title: "Secure Collaboration", description: "Share insights without sharing data" },
    ],
  },
  {
    id: "sys-pin-tts",
    slug: "sys-pin-tts",
    tagline: "NATURAL VOICE SYNTHESIS",
    name: "TTS Model",
    shortDescription: "Advanced text-to-speech AI model delivering natural, human-like voice synthesis for enterprise applications.",
    description: "Our Sys Pin TTS Model leverages cutting-edge deep learning to generate high-quality, natural-sounding speech from text. Built with state-of-the-art neural networks, it supports multiple languages, voices, and emotional tones, making it ideal for voice assistants, accessibility tools, content creation, and automated communication systems.",
    iconName: "Volume2" as const,
    color: "#3b82f6", // Blue-500
    gradient: "from-blue-500 to-indigo-600",
    hasVideo: true,
    videoSrc: "/video/tts-web.mp4",
    features: [
      "Neural voice synthesis",
      "Multi-language support",
      "Emotional tone control",
      "Real-time generation",
      "API integration",
      "Custom voice training",
    ],
    benefits: [
      { title: "Natural Speech", description: "Human-like voice quality and intonation" },
      { title: "Low Latency", description: "Real-time text-to-speech conversion" },
      { title: "Scalable", description: "Enterprise-ready for high-volume applications" },
    ],
  },
  {
    id: "encryption-platform",
    slug: "encryption-platform",
    tagline: "ADVANCED DATA PROTECTION",
    name: "Encryption & Security Platform",
    shortDescription: "Enterprise-grade encryption solutions with advanced cryptographic protocols for secure data storage, transmission, and access control.",
    description: "Our Encryption & Security Platform provides robust cryptographic solutions for enterprises requiring the highest levels of data protection. Built with state-of-the-art encryption algorithms and key management systems, it ensures end-to-end security for sensitive data across storage, transmission, and processing workflows. The platform supports multiple encryption standards, secure key exchange protocols, and granular access controls for comprehensive data security.",
    iconName: "Key" as const,
    color: "#8b5cf6", // Violet-500
    gradient: "from-violet-500 to-purple-600",
    hasVideo: true,
    videoSrc: "/video/he-web.mp4",
    features: [
      "Advanced cryptographic algorithms",
      "Secure key management",
      "End-to-end encryption",
      "Multi-layer data protection",
      "Compliance-ready architecture",
      "Granular access controls",
    ],
    benefits: [
      { title: "Military-Grade", description: "Industry-leading encryption standards" },
      { title: "Zero Trust", description: "Comprehensive data protection at every layer" },
      { title: "Compliance Ready", description: "Meet regulatory requirements effortlessly" },
    ],
  },
  {
    id: "document-processing",
    slug: "document-processing",
    tagline: "INTELLIGENT DOCUMENT AUTOMATION",
    name: "Document Processing",
    shortDescription: "Advanced AI that restores, extracts, and summarizes data from low-quality scans and complex legal documents.",
    description: "Transform your document workflow with our advanced Intelligent Document Processing engine, capable of handling challenging inputs—from low-quality scans to dense legal affidavits. Our system combines high-precision OCR with Natural Language Processing (NLP) to restore legibility, extract critical data, and generate intelligent summaries, turning unstructured paperwork into structured, actionable insights.",
    iconName: "FileText" as const,
    color: "#06b6d4", // Cyan-500
    gradient: "from-cyan-500 to-blue-600",
    hasVideo: true,
    videoSrc: "/video/idp-animation-1766488235755.mp4",
    features: [
      "Low-quality scan enhancement",
      "Legal document summarization",
      "Handwriting recognition",
      "NLP-based entity extraction",
      "Automated classification",
      "Batch processing support",
    ],
    benefits: [
      { title: "90% Faster", description: "Accelerate document processing times" },
      { title: "99% Accuracy", description: "High-precision data extraction" },
      { title: "Scalable", description: "Process millions of documents effortlessly" },
    ],
  },
  {
    id: "etappal-automation",
    slug: "etappal-automation",
    tagline: "SMART GOVERNMENT WORKFLOWS",
    name: "eTappal Automation",
    shortDescription: "AI/ML-powered system for automated analysis, categorization, and digital routing of administrative documents.",
    description: "Streamline administrative operations with our eTappal Workflow Automation. This AI-driven solution automatically ingests scanned or digital eTappals, extracts subject and content using advanced NLP, categorizes them, and intelligently routes them to the appropriate officers. By replacing manual segregation with automated workflows, we ensure faster processing, accurate delivery, and complete digital traceability.",
    iconName: "FileStack" as const,
    color: "#ec4899", // Pink-500
    gradient: "from-pink-500 to-rose-600",
    hasVideo: true,
    videoSrc: "/video/nascom-dataprocess-1767074832190.mp4",
    demoUrl: "https://huggingface.co/spaces/Abhimanyu42/etappal-ai",
    features: [
      "Automated eTappal Analysis",
      "Intelligent Content Extraction",
      "Subject Categorization",
      "Auto-Routing to Officers",
      "Digital Record Maintenance",
      "Traceability & Audit Logs",
    ],
    benefits: [
      { title: "Zero Manual Routing", description: "Fully automated document distribution" },
      { title: "80% Faster", description: "Significantly reduce processing time" },
      { title: "100% Traceable", description: "Complete digital audit trails" },
    ],
  },
]

export type Product = typeof products[number]
export type IconName = Product["iconName"]

export function getProductBySlug(slug: string): Product | undefined {
  return products.find((p) => p.slug === slug)
}
